0.1.9

diff --git a/opt/teamviewer-installer b/opt/teamviewer-installer
--- a/opt/teamviewer-installer
+++ b/opt/teamviewer-installer
@@ -3,7 +3,7 @@
 # Teamviewer On-Line Installer is a script which can download and install Teamviewer for Linux (Debian package)
 # Created by Paweł "pavroo" Pijanowski 2015/08/27
 # Copyright 2015-2018 under the GNU GPL2 License
-# Last updated 2018/03/16
+# Last updated 2018/04/01
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-teamviewer"
@@ -41,10 +41,11 @@ OKEXIT=" --button=Ok:0 --button=$LOCAL1:1 "
 MSGBOX=" --button=Ok:0 "
 MENU="--list --column=$LOCAL2 --column=$LOCAL3"
 TITLETEXT="$LOCAL4"
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 # check internet connection
@@ -65,7 +66,9 @@ if [ "$?" != "0" ]; then
 
 else
 
-	$SPARKYXTERM -e "apt-get update && apt-get install teamviewer && apt-get install -f"
+	$SPARKYXTERM "apt-get update"
+	$SPARKYXTERM "apt-get install teamviewer"
+	$SPARKYXTERM "apt-get install -f"
 
 fi
 
